# Database Configuration
DATABASE_URI = None
DATABASE_NAME = None

# Bot Configuration
BOT_TOKEN = NzczMzY0MjI0NjQxNzI4NTQz.X6IJjw.iRNUPHXhK6BlC1ippxdO6xAKW30
SECRET_KEY = 7xOVtUYsl8YnNttPlas4VdnkJ_TEMdZV
REDIS_CONF = {}

# DBL
DBL_TOKEN = None
DBL_SECRET = None

# Webhooks
STRIPE_KEY = None
STRIPE_WEBHOOK_SECRET = None
GITHUB_WEBHOOK_SECRET = None
